tap "nkzw-tech/tap", trusted: { casks: ["codiff"] }
tap "nubjs/tap", trusted: { formulae: ["nub"] }
tap "oven-sh/bun", trusted: { formulae: ["bun"] }
tap "planetscale/tap", trusted: { formulae: ["pscale"] }
tap "stablyai/orca", trusted: { casks: ["orca"] }

brew "asc"
brew "bat"
brew "bun"
brew "caddy"
brew "cloudflared"
brew "cocoapods"
brew "composer"
brew "direnv"
brew "eza"
brew "fish"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-flow-next"
brew "glow"
brew "htop"
brew "httpie"
brew "jq"
brew "lazygit"
brew "mise"
brew "mole"
brew "nub"
brew "ollama"
brew "php"
brew "php@8.3"
brew "php@8.4"
brew "pi-coding-agent"
brew "pie"
brew "pnpm"
brew "portless"
brew "pscale"
brew "railway"
brew "rust"
brew "starship"
brew "timg"
brew "tlrc"
brew "tmux"
brew "uv"
brew "watch"
brew "watchman"
brew "yt-dlp"
brew "zoxide"

cask "1password"
cask "1password-cli"
cask "android-studio"
cask "block-buzz"
cask "claude"
cask "claude-code"
cask "cleanmymac-cli"
cask "coderabbit"
cask "codex"
cask "codexbar"
cask "codiff"
cask "hammerspoon"
cask "iterm2"
cask "orbstack"
cask "stablyai/orca/orca"
cask "paper-design"
cask "phpstorm"
cask "telegram"
cask "termius"
cask "tldraw"
cask "tower"
cask "visual-studio-code"
